# config/specialties.py
# Comprehensive list of specialties for candidates

SPECIALTIES = [
    # WELDING
    'Welding - MIG',
    'Welding - TIG',
    'Welding - Stick (SMAW)',
    'Welding - Flux Core',
    'Pipe Welding',
    'Structural Welding',
    'Aluminum Welding',
    'Stainless Steel Welding',
    'Certified Welder',
    
    # ELECTRICAL
    'Electrical - High Voltage',
    'Electrical - Low Voltage',
    'Electrical Wiring',
    'Panel Installation',
    'Troubleshooting & Repair',
    'Industrial Electrical',
    'Building Electrical',
    'Solar Installation',
    'Certified Electrician',
    'PLC Programming',
    
    # MECHANICS - GENERAL
    'General Mechanic',
    'Equipment Mechanic',
    'Machinery Technician',
    'Maintenance Mechanic',
    'Industrial Mechanic',
    'Heavy Equipment Mechanic',
    
    # MECHANICS - AUTOMOTIVE
    'Automotive Mechanic',
    'Engine Mechanic',
    'Transmission Repair',
    'Brake Systems',
    'Suspension & Alignment',
    'Diesel Engine Mechanic',
    'Heavy Truck Mechanic',
    'Auto Electrician',
    'Certified ASE Mechanic',
    
    # MECHANICS - INDUSTRIAL/MAINTENANCE
    'Predictive Maintenance',
    'Preventive Maintenance',
    'CNC Machine Operator',
    'Lathe Operator',
    'Precision Machinist',
    'Hydraulics Technician',
    'Pneumatics Technician',
    'Bearing & Seal Specialist',
    
    # HVAC
    'HVAC Technician',
    'Air Conditioning Technician',
    'Heating Systems',
    'Refrigeration Technician',
    'HVAC Installation',
    'EPA Certified HVAC',
    'Ventilation Systems',
    
    # PLUMBING
    'Plumber',
    'Pipe Fitter',
    'Plumbing Installation',
    'Drainage Systems',
    'Water Treatment',
    'Gas Fitting',
    'Backflow Prevention',
    'Certified Plumber',
    
    # CONSTRUCTION & CARPENTRY
    'Carpenter',
    'Rough Carpentry',
    'Finish Carpentry',
    'Framing',
    'Masonry',
    'Concrete Work',
    'Tile Installation',
    'Drywall Installation',
    'Roofing',
    'Formwork Specialist',
    
    # PAINTING & FINISHING
    'Painter',
    'Industrial Painter',
    'Spray Painting',
    'Surface Preparation',
    'Coating Specialist',
    'Finish Carpenter',
    
    # OPERATORS
    'Forklift Operator',
    'Crane Operator',
    'Excavator Operator',
    'Loader Operator',
    'Dozer Operator',
    'Heavy Equipment Operator',
    'Scissor Lift Operator',
    'Reach Truck Operator',
    'Certified Equipment Operator',
    
    # WELDING - ADVANCED
    'Robotic Welding',
    'Underwater Welding',
    'Aerospace Welding',
    'Pressure Vessel Welding',
    'Code Inspector Welder',
    
    # FABRICATION & METALWORK
    'Metal Fabricator',
    'Sheet Metal Fabrication',
    'Steel Fabrication',
    'Aluminum Fabrication',
    'Ironworker',
    'Blacksmith',
    'Tool & Die Maker',
    
    # QUALITY & INSPECTION
    'Quality Control Inspector',
    'Inspection Technician',
    'NDT Technician (Non-Destructive Testing)',
    'Ultrasonic Testing',
    'X-Ray Inspection',
    'Dimensional Inspector',
    'Surface Inspector',
    
    # SAFETY & COMPLIANCE
    'Safety Officer',
    'Health & Safety Technician',
    'OSHA Certified',
    'Fire Safety Inspector',
    'Environmental Health & Safety',
    
    # LOGISTICS & WAREHOUSE
    'Warehouse Manager',
    'Inventory Specialist',
    'Logistics Coordinator',
    'Shipping & Receiving',
    'Material Handler',
    'Stock Keeper',
    
    # PRODUCTION & MANUFACTURING
    'Production Supervisor',
    'Production Technician',
    'Assembly Technician',
    'Line Operator',
    'Process Technician',
    'Quality Technician',
    'Manufacturing Engineer',
    
    # MAINTENANCE & JANITORIAL
    'Janitor/Cleaner',
    'Building Maintenance',
    'Facilities Maintenance',
    'General Handyman',
    'Landscaping',
    'Grounds Keeper',
    
    # SPECIALIZED TRADES
    'Glazier',
    'Glass Installation',
    'Locksmith',
    'Door & Hardware Installation',
    'Insulation Technician',
    'Weatherization Specialist',
    'Scaffolding Specialist',
    'Signage Installation',
    
    # ENTRY LEVEL & GENERAL
    'Laborer',
    'General Laborer',
    'Helper',
    'Apprentice',
    'Trainee',
    'Unskilled Worker',
    'Assembly Helper',
    'Production Helper',
    
    # SUPERVISORY & MANAGEMENT
    'Supervisor',
    'Team Lead',
    'Shift Manager',
    'Site Manager',
    'Project Manager',
    'Operations Manager',
    'Maintenance Manager',
    'Production Manager',
]

SPECIALTIES_BY_CATEGORY = {
    'Welding & Metal Fabrication': [
        'Welding - MIG',
        'Welding - TIG',
        'Welding - Stick (SMAW)',
        'Welding - Flux Core',
        'Pipe Welding',
        'Structural Welding',
        'Aluminum Welding',
        'Stainless Steel Welding',
        'Certified Welder',
        'Robotic Welding',
        'Underwater Welding',
        'Aerospace Welding',
        'Pressure Vessel Welding',
        'Code Inspector Welder',
        'Metal Fabricator',
        'Sheet Metal Fabrication',
        'Steel Fabrication',
        'Aluminum Fabrication',
        'Ironworker',
        'Blacksmith',
        'Tool & Die Maker'
    ],
    'Electrical & Automation': [
        'Electrical - High Voltage',
        'Electrical - Low Voltage',
        'Electrical Wiring',
        'Panel Installation',
        'Troubleshooting & Repair',
        'Industrial Electrical',
        'Building Electrical',
        'Solar Installation',
        'Certified Electrician',
        'PLC Programming'
    ],
    'Mechanics & Machining': [
        'General Mechanic',
        'Equipment Mechanic',
        'Machinery Technician',
        'Maintenance Mechanic',
        'Industrial Mechanic',
        'Heavy Equipment Mechanic',
        'Automotive Mechanic',
        'Engine Mechanic',
        'Transmission Repair',
        'Brake Systems',
        'Suspension & Alignment',
        'Diesel Engine Mechanic',
        'Heavy Truck Mechanic',
        'Auto Electrician',
        'Certified ASE Mechanic',
        'Preventive Maintenance',
        'Predictive Maintenance',
        'CNC Machine Operator',
        'Lathe Operator',
        'Precision Machinist',
        'Hydraulics Technician',
        'Pneumatics Technician',
        'Bearing & Seal Specialist'
    ],
    'HVAC & Plumbing': [
        'HVAC Technician',
        'Air Conditioning Technician',
        'Heating Systems',
        'Refrigeration Technician',
        'HVAC Installation',
        'EPA Certified HVAC',
        'Ventilation Systems',
        'Plumber',
        'Pipe Fitter',
        'Plumbing Installation',
        'Drainage Systems',
        'Water Treatment',
        'Gas Fitting',
        'Backflow Prevention',
        'Certified Plumber'
    ],
    'Construction & Carpentry': [
        'Carpenter',
        'Rough Carpentry',
        'Finish Carpentry',
        'Framing',
        'Masonry',
        'Concrete Work',
        'Tile Installation',
        'Drywall Installation',
        'Roofing',
        'Formwork Specialist'
    ],
    'Painting & Finishing': [
        'Painter',
        'Industrial Painter',
        'Spray Painting',
        'Surface Preparation',
        'Coating Specialist'
    ],
    'Heavy Equipment & Operations': [
        'Forklift Operator',
        'Crane Operator',
        'Excavator Operator',
        'Loader Operator',
        'Dozer Operator',
        'Heavy Equipment Operator',
        'Scissor Lift Operator',
        'Reach Truck Operator',
        'Certified Equipment Operator'
    ],
    'Quality & Safety': [
        'Quality Control Inspector',
        'Inspection Technician',
        'NDT Technician (Non-Destructive Testing)',
        'Ultrasonic Testing',
        'X-Ray Inspection',
        'Dimensional Inspector',
        'Surface Inspector',
        'Safety Officer',
        'Health & Safety Technician',
        'OSHA Certified',
        'Fire Safety Inspector',
        'Environmental Health & Safety'
    ],
    'Logistics & Warehousing': [
        'Warehouse Manager',
        'Inventory Specialist',
        'Logistics Coordinator',
        'Shipping & Receiving',
        'Material Handler',
        'Stock Keeper'
    ],
    'Supervision & Engineering': [
        'Supervisor',
        'Team Lead',
        'Shift Manager',
        'Site Manager',
        'Project Manager',
        'Operations Manager',
        'Maintenance Manager',
        'Production Manager',
        'Production Supervisor',
        'Production Technician',
        'Assembly Technician',
        'Line Operator',
        'Process Technician',
        'Quality Technician',
        'Manufacturing Engineer'
    ],
    'General Trades & Helpers': [
        'Laborer',
        'General Laborer',
        'Helper',
        'Apprentice',
        'Trainee',
        'Unskilled Worker',
        'Assembly Helper',
        'Production Helper',
        'Janitor/Cleaner',
        'Building Maintenance',
        'Facilities Maintenance',
        'General Handyman',
        'Landscaping',
        'Grounds Keeper',
        'Glazier',
        'Glass Installation',
        'Locksmith',
        'Door & Hardware Installation',
        'Insulation Technician',
        'Weatherization Specialist',
        'Scaffolding Specialist',
        'Signage Installation'
    ]
}